import { state, els, escapeHtml, asArray, formatDate, formatDateTime, appPath, api, backlogCases } from './shared.js?v=2026-07-15-control-center-editorial-v1';
const trendClass = trend => ['improved','stable','worsened','attention','insufficient'].includes(trend) ? trend : 'insufficient';
const metricValue = value => Number.isInteger(Number(value)) ? String(Number(value)) : String(Number(value || 0).toFixed(1));
function metricCard(title,value,text,tone='') { return `<article class="cc-metric ${tone ? `cc-metric--${tone}` : ''}"><span>${escapeHtml(title)}</span><strong>${escapeHtml(value)}</strong><p>${escapeHtml(text)}</p></article>`; }
function switcher() { return `<div class="cc-segment cc-development-switch"><button class="${state.developmentMode === 'project' ? 'is-active' : ''}" data-development-mode="project">Projektstatus</button><button class="${state.developmentMode === 'seo' ? 'is-active' : ''}" data-development-mode="seo">SEO & Reichweite</button></div>`; }
function componentRow(item) { const evidence=asArray(item.evidence).map(metric=>{const sign=Number(metric.delta)>0?'+':'';return `<div><span>${escapeHtml(metric.label)}</span><strong>${escapeHtml(metricValue(metric.current))}${escapeHtml(metric.unit||'')}</strong><small>${escapeHtml(metricValue(metric.previous))}${escapeHtml(metric.unit||'')} → ${sign}${escapeHtml(metricValue(metric.delta))}${escapeHtml(metric.unit||'')}</small></div>`;}).join(''); const details=evidence?`<details class="cc-component-details"><summary>Messwerte anzeigen</summary><div class="cc-component-evidence">${evidence}</div></details>`:'<p class="cc-component-note">Ein belastbarer Sieben-Tage-Vergleich entsteht automatisch, sobald genügend Verlaufssnapshots vorliegen.</p>'; const run=item.run_url?`<a href="${escapeHtml(item.run_url)}" target="_blank" rel="noopener">Letzten Lauf öffnen</a>`:''; return `<article class="cc-component-row"><header><div><h3>${escapeHtml(item.label)}</h3><p>${escapeHtml(item.technical_message||'Kein aktueller Prozesshinweis.')}</p></div><span class="cc-component-trend cc-component-trend--${trendClass(item.trend)}">${escapeHtml(item.trend_label||'Datenbasis noch zu klein')}</span></header>${details}${run?`<div class="cc-component-link">${run}</div>`:''}</article>`; }
function bind(){document.querySelectorAll('[data-development-mode]').forEach(button=>button.addEventListener('click',()=>{state.developmentMode=button.dataset.developmentMode;renderDevelopment();}));}
function renderProject(){const data=state.development||{},quality=data.content_quality||{},process=data.automation?.process_health||{},processProblem=['attention','unknown'].includes(process.status),improvement=data.component_improvement||{},period=improvement.comparison_at?`Vergleich seit ${formatDate(improvement.comparison_at)}`:'Verlauf wird aufgebaut';els.view.classList.remove('cc-view--seo');els.view.innerHTML=`${switcher()}<section class="cc-development-head"><span class="cc-kicker">Gesamtprojekt</span><h2>${escapeHtml(data.operator_status||data.summary?.label||'Entwicklungsstand')}</h2><p>Datenstand ${escapeHtml(formatDateTime(data.generated_at))}</p></section><section class="cc-metric-grid cc-metric-grid--compact">${metricCard('Content',quality.coverage_percent>=100?'Datenbasis vollständig':`${quality.coverage_percent??0} % Datenbasis`,`${quality.open_quality_reviews||0} offene Qualitätsprüfungen`,quality.open_quality_reviews>0?'attention':'good')}${metricCard('Prozesse',processProblem?'Prüfen':'Okay',process.message||'Kein bekannter Prozessfehler',processProblem?'attention':'good')}${metricCard('Backlog',String(backlogCases().length),'Offene geplante Verbesserungen',backlogCases().length>0?'':'good')}</section><section class="cc-component-improvement"><header class="cc-component-head"><div><span class="cc-kicker">Automatisierte Verbesserung</span><h2>Wie entwickeln sich die Projektbausteine?</h2><p>Bewertung aus Betriebszustand, Qualität, Lernwirkung und einem mindestens sieben Tage alten Vergleich.</p></div><span class="cc-component-period">${escapeHtml(period)}</span></header><div class="cc-component-list">${asArray(improvement.items).map(componentRow).join('')||'<div class="cc-empty">Noch keine Bausteindaten verfügbar.</div>'}</div></section>`;bind();}
function renderSeo(){els.view.classList.add('cc-view--seo');els.view.innerHTML=`${switcher()}<div class="cc-seo-frame-wrap"><iframe class="cc-seo-frame" src="${escapeHtml(appPath('/intern/seo-dashboard/?embed=1'))}" title="SEO- und Mehrwert-Dashboard" loading="eager"></iframe></div>`;bind();}
export async function renderDevelopment(){if(!state.development){els.view.innerHTML='<div class="cc-empty">Entwicklungsdaten werden geladen …</div>';try{state.development=await api('/api/control-center/development.php');}catch(error){els.view.innerHTML=`<div class="cc-empty cc-empty--large">${escapeHtml(error.message)}</div>`;return;}}if(state.developmentMode==='seo')renderSeo();else renderProject();}
