(() => {
  'use strict';
  const card=document.getElementById('organizer-dashboard-pilot-card');
  if(!card)return;
  const safe=value=>String(value??'').trim();
  const escape=value=>safe(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
  async function json(url,options={}){const response=await fetch(url,{credentials:'same-origin',headers:{Accept:'application/json',...(options.headers||{})},...options});const data=await response.json().catch(()=>null);if(!response.ok)throw Object.assign(new Error(data?.message||'request_failed'),{status:response.status});return data?.data||data;}
  function phaseLabel(phase){return ({onboarding:'Onboarding läuft',activation_ready:'Aktivierung wird vorbereitet',active:'Pilotphase läuft'})[phase]||phase||'Onboarding';}
  function scopes(rows=[]){return rows.filter(row=>['events','activities'].includes(row.scope_key)).map(row=>`${row.scope_key==='events'?'Veranstaltungen':'Aktivitäten'}: ${row.is_unlimited?'vereinbarter Rahmen':row.limit_value||'–'}${row.period_unit==='pilot_month'?' je Pilotmonat':row.period_unit==='concurrent'?' gleichzeitig':''}`).join(' · ');}
  function contentForm(gate4){const eventScope=(gate4.scopes||[]).some(row=>row.scope_key==='events');const activityScope=(gate4.scopes||[]).some(row=>row.scope_key==='activities');return `<form class="content-form organizer-pilot-content-form" id="organizer-pilot-content-form"><div class="content-form-grid"><label class="content-field"><span class="content-field__label">Inhaltstyp</span><select class="content-field__control" name="content_type">${eventScope?'<option value="event">Veranstaltung</option>':''}${activityScope?'<option value="activity">Aktivität</option>':''}</select></label><label class="content-field"><span class="content-field__label">Titel *</span><input class="content-field__control" name="title" required></label><label class="content-field"><span class="content-field__label">Ort / Anbieter *</span><input class="content-field__control" name="location_name" required></label><label class="content-field" data-pilot-event-date><span class="content-field__label">Datum</span><input class="content-field__control" name="start_date" type="date"></label><label class="content-field content-field--full"><span class="content-field__label">Öffentliche Adresse / Treffpunkt</span><input class="content-field__control" name="location_address"></label><label class="content-field content-field--full"><span class="content-field__label">Beschreibung / Hinweise</span><textarea class="content-field__control" name="description_text" rows="3"></textarea></label><label class="content-field content-field--full content-field--checkbox"><span class="content-field__hint"><input name="location_public_confirmed" type="checkbox" required> Ich darf diesen Ort öffentlich nennen und den Inhalt einreichen.</span></label></div><div class="content-actions content-actions--inline"><button class="content-cta content-cta--primary" type="submit">Kostenlos zur redaktionellen Prüfung einreichen</button></div><p class="content-note" data-pilot-submit-status>Keine Zahlung, kein Stripe-Checkout und keine automatische Veröffentlichung.</p></form>`;}
  function render(data){const gate4=data.gate4||{},pilot=gate4.pilot||{},candidate=data.candidate||{},gate3=candidate.gate3||{};card.hidden=false;card.innerHTML=`<div class="content-form-section-head"><div><span class="content-kicker">Kostenloser Startpartner-Pilot</span><h2>${escape(phaseLabel(gate4.phase))}</h2></div><span class="organizer-status-badge">${escape(gate4.phase||'onboarding')}</span></div><p>${escape(gate4.active?'Die sechsmonatige Pilotphase läuft. Es gibt keine automatische kostenpflichtige Verlängerung.':'Die Einrichtung läuft. Die sechs Monate beginnen erst nach vollständiger Aktivierung und dem ersten veröffentlichten Inhalt.')}</p><dl class="organizer-tariff-table"><div><dt>Vereinbarter Umfang</dt><dd>${escape(scopes(gate3.scopes)||'Wird eingerichtet')}</dd></div><div><dt>Aktivierung</dt><dd>${escape(pilot.activation_date_local||'Noch nicht gestartet')}</dd></div><div><dt>Geplantes Ende</dt><dd>${escape(pilot.planned_end_date||'Noch offen')}</dd></div><div><dt>Veröffentlichte Pilotinhalte</dt><dd>${escape(String((gate4.content_links||[]).filter(row=>row.status==='approved').length))}</dd></div></dl><details class="content-disclosure"><summary>Neuen Pilotinhalt vorbereiten</summary>${contentForm({...gate4,scopes:gate3.scopes||[]})}</details>`;bindForm();}
  function bindForm(){const form=document.getElementById('organizer-pilot-content-form');if(!form)return;const type=form.elements.content_type,dateRow=form.querySelector('[data-pilot-event-date]');const sync=()=>{dateRow.hidden=type.value!=='event';form.elements.start_date.required=type.value==='event';};type.addEventListener('change',sync);sync();form.addEventListener('submit',async event=>{event.preventDefault();if(!form.reportValidity())return;const button=form.querySelector('button[type="submit"]'),status=form.querySelector('[data-pilot-submit-status]');button.disabled=true;status.textContent='Einreichung wird vorbereitet …';const values=Object.fromEntries(new FormData(form).entries());const payload={...values,location_public_confirmed:form.elements.location_public_confirmed.checked,client_reference:`gate4-241-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`};try{const result=await json('/api/startpartner/content.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});status.textContent=`Einreichung ${result.submission_id||result.content_link?.submission_id||''} wurde ohne Zahlung zur redaktionellen Prüfung vorbereitet.`;form.reset();}catch(error){status.textContent=error.message||'Die Einreichung konnte nicht vorbereitet werden.';}finally{button.disabled=false;}});}
  json('/api/organizer-portal/pilot.php').then(render).catch(error=>{if(![401,404].includes(error.status))console.warn('Organizer pilot state failed.',error);});
})();
