import fs from 'node:fs';
const read=path=>fs.readFileSync(path,'utf8');
const html=read('steuerzentrale/index.html'); const loader=read('js/control-center.js');
const moduleNames=['shared','app','backlog','review','review-render','review-actions','manage','manage-render','manage-actions','development'];
const moduleSources=Object.fromEntries(moduleNames.map(name=>[name,read(`js/control-center/${name}.js`)])); const modules=Object.values(moduleSources).join('\n');
const shared=moduleSources.shared,app=moduleSources.app,backlog=moduleSources.backlog,reviewActions=moduleSources['review-actions'],reviewRender=moduleSources['review-render'];
const seo=read('js/control-center-seo-embed.js'),style=read('css/style.css'),css=read('css/control-center-editorial.css'),exceptionCss=read('css/control-center-exception-review.css');
const presentation=read('api/control-center/_presentation.php'),caseApi=read('api/control-center/case.php'),actionApi=read('api/control-center/action.php');
const taskContract=read('api/control-center/_event_review_tasks.php'),taskWriteback=read('api/control-center/_event_review_writeback.php');
const directInboxWriteback=read('api/control-center/_inbox_decision_writeback.php'),verifiedSourceWriteback=read('api/control-center/_verified_source_writeback.php'),sourceReconciliation=read('api/control-center/_source_reconciliation.php');
const sheetInboxSource=read('api/control-center/_sheet_inbox_source.php'),submissionSource=read('api/control-center/_submission_source.php'),sources=read('api/control-center/_sources.php');
const backlogApi=read('api/growth-backlog/list.php'),backlogLib=read('api/growth-backlog-lib.php'),backlogCreate=read('api/growth-backlog/create.php'),backlogUpdate=read('api/growth-backlog/update.php');
const errors=[];
const buildKey='2026-07-24-mobile-exception-review-v1';
const cssGovernanceKey='2026-06-22-css-governance-v1';
for(const asset of ['control-center-environment.js','control-center.js','control-center-seo-embed.js'])if(!html.includes(asset))errors.push(`required script missing: ${asset}`);
for(const asset of ['control-center-source-editors.js','control-center-final-bridge.js','control-center-stability.js','control-center-publication.js','control-center-development.js','control-center-integrations.js'])if(html.includes(asset))errors.push(`overlay controller still loaded: ${asset}`);
for(const marker of ['control-center/app.js','import(path)','2026-07-16-exception-review-v1',buildKey])if(!loader.includes(marker))errors.push(`module loader missing: ${marker}`);
if(!html.includes(`control-center.js?v=${buildKey}`))errors.push('top-level control-center script cache key is stale');
if(!html.includes(`style.css?v=${cssGovernanceKey}`))errors.push('top-level control-center stylesheet must keep the CSS governance key');
if(!style.includes(`control-center-exception-review.css?v=${cssGovernanceKey}`))errors.push('exception-review stylesheet must keep the CSS governance key');
if(!app.includes(`review.js?v=${buildKey}`))errors.push('app review-module cache key is stale');
if(!moduleSources.review.includes(`review-render.js?v=${buildKey}`))errors.push('review renderer cache key is stale');
for(const marker of ['edit_and_approve','decision_class','operation_id','Ablehnungsgrund auswählen','source_fingerprint','content_fingerprint','current_description_hash','data-manage-details','Live öffnen','Öffentliche Wirkung wird geprüft · Versuch','be_cc_draft:','Automatisierte Verbesserung','Promise.allSettled','resolve_review_task','task_revision','data-review-task-resolution','visual_asset_id'])if(!modules.includes(marker)&&!caseApi.includes(marker))errors.push(`frontend contract missing: ${marker}`);
for(const marker of ['review_contract','be_cc_event_candidate_review_contract','resolve_review_task','review_tasks'])if(!presentation.includes(marker)&&!caseApi.includes(marker))errors.push(`presentation contract missing: ${marker}`);
for(const marker of ['field_evidence','review_tasks','task_revision','time_not_published','visual_asset_id','visual_gap_id','candidate_ready'])if(!taskContract.includes(marker))errors.push(`event task contract missing: ${marker}`);
for(const marker of ['be_cc_resolve_event_review_task','be_cc_inbox_direct_canonical_update_verified','source_verified','review_contract_recheck','review_task_resolved'])if(!taskWriteback.includes(marker))errors.push(`event task writeback missing: ${marker}`);
for(const marker of ['cc-review-task','cc-review-asset','cc-evidence','cc-asset-option','cc-mobile-priority','cc-duplicate-comparison','cc-mobile-decision','cc-review-task-evidence--mobile','cc-mobile-case-options'])if(!exceptionCss.includes(marker))errors.push(`exception review CSS missing: ${marker}`);
for(const marker of ['Offen · empfohlene Reihenfolge','Abgeschlossen','<details class="cc-labor-row cc-roadmap-row','<summary>','cc-labor-detail','cc-backlog-new','data-backlog-edit','data-backlog-status','Details &amp; Bearbeiten','/api/growth-backlog/create.php','/api/growth-backlog/update.php'])if(!backlog.includes(marker))errors.push(`backlog frontend contract missing: ${marker}`);
for(const marker of ['gbl_read_snapshot','counts','completed'])if(!backlogApi.includes(marker)&&!backlogLib.includes(marker))errors.push(`backlog source contract missing: ${marker}`);
for(const marker of ['why_relevant','recommended_action','expected_benefit','type'])if(!backlogCreate.includes(marker)||!backlogUpdate.includes(marker))errors.push(`structured backlog writeback missing: ${marker}`);
for(const marker of ["['edit', 'complete', 'reopen']",'expected_updated_at',"'status' => 'open'","'status' => 'completed'"])if(!backlogUpdate.includes(marker))errors.push(`two-status backlog update contract missing: ${marker}`);
for(const forbidden of ['data-backlog-action','submitBacklog(','handleBacklog(','backlogCases()','<article class="cc-roadmap-item','cc-roadmap-summary','Informations- und Reihenfolgeansicht','Punkte insgesamt'])if(backlog.includes(forbidden))errors.push(`backlog contains obsolete work-queue or header-block marker: ${forbidden}`);
for(const marker of ['timeoutMs:70000','assertCompletion','throwOnError:true','vollständig geprüft','Entscheidung wurde gespeichert, aber die Ansicht konnte nicht konsistent aktualisiert werden','Teilaktion wird gespeichert, zurückgelesen und neu bewertet'])if(!reviewActions.includes(marker))errors.push(`end-to-end review feedback missing: ${marker}`);
for(const marker of ['Offene Prüfaufgaben','Geprüfte Gesamtfassung','Event entscheidungsreif','data-review-task-resolution','Kandidat und Bestand','Entscheidung auswählen','matched_title','matched_date','matched_location','formatMatchScore','trueWaiting','cc-mobile-priority','aria-expanded'])if(!reviewRender.includes(marker))errors.push(`exception review renderer missing: ${marker}`);
if(reviewRender.includes('matched_time'))errors.push('existing-event time must not be rendered without an API contract');
for(const marker of ['caseIsReviewVisible','snoozed_until','activeCases()'])if(!shared.includes(marker))errors.push(`review visibility contract missing: ${marker}`);
for(const marker of ["await api('/api/control-center/overview.php'","/api/control-center/cases.php?active=1",'throwOnError'])if(!app.includes(marker))errors.push(`serialized load contract missing: ${marker}`);
const overviewIndex=app.indexOf("await api('/api/control-center/overview.php'");const casesIndex=app.indexOf("api('/api/control-center/cases.php?active=1'");if(overviewIndex<0||casesIndex<0||overviewIndex>=casesIndex)errors.push('source reconciliation must complete before active case loading');
if(app.includes("Promise.all([\n      api('/api/control-center/overview.php')"))errors.push('overview and active cases must not load concurrently');
for(const marker of ['_verified_source_writeback.php','_source_reconciliation.php','_event_review_writeback.php','be_cc_assert_case_postcondition','source_verified','completion','be_cc_writeback_inbox_approve_verified','be_cc_writeback_audit_verified'])if(!actionApi.includes(marker))errors.push(`action end-to-end contract missing: ${marker}`);
for(const marker of ['google_sheets_direct_batch','values:batchUpdate','BE_CC_INBOX_DIRECT_HTTP_TIMEOUT_SECONDS','BE_CC_INBOX_DIRECT_VERIFY_ATTEMPTS','be_cc_verify_inbox_writeback_direct','be_cc_inbox_tab_name','be_cc_inbox_range','be_cc_inbox_direct_canonical_plan'])if(!directInboxWriteback.includes(marker))errors.push(`bounded direct inbox writeback missing: ${marker}`);
for(const marker of ['BE_CC_SOURCE_HTTP_TIMEOUT_SECONDS = 8','BE_CC_SOURCE_VERIFY_ATTEMPTS = 2','be_cc_source_batch_update','be_cc_writeback_inbox_approve_verified','be_cc_writeback_audit_verified','be_cc_source_verify_fields'])if(!verifiedSourceWriteback.includes(marker))errors.push(`shared verified source writeback missing: ${marker}`);
for(const marker of ['be_cc_source_terminal_target','be_cc_reconcile_source_case','be_cc_assert_case_postcondition','be_cc_case_is_review_visible'])if(!sourceReconciliation.includes(marker))errors.push(`source reconciliation contract missing: ${marker}`);
for(const [name,source] of [['sheet inbox',sheetInboxSource],['submissions',submissionSource],['content audit/json sources',sources]])if(!source.includes('be_cc_reconcile_source_case'))errors.push(`${name} source does not reconcile terminal local cases`);
for(const forbidden of ['be_cc_update_sheet_row_by_header(','be_cc_verify_inbox_writeback($source'])if(directInboxWriteback.includes(forbidden))errors.push(`slow legacy inbox writeback call remains: ${forbidden}`);
if(!style.includes('control-center-editorial.css'))errors.push('editorial CSS is not in governance entrypoint');
for(const marker of ['cc-fact-grid','cc-gate--blocked','cc-dialog--wide','cc-history','cc-backlog-toolbar','cc-roadmap-actions','cc-roadmap-affordance','.cc-dialog .cc-fact-grid','grid-template-columns:minmax(0,1fr)!important','overflow-x:hidden'])if(!css.includes(marker))errors.push(`editorial CSS marker missing: ${marker}`);
if(modules.includes('new MutationObserver('))errors.push('core modules must not patch their own UI through MutationObserver');
if(!modules.includes("appPath('/intern/seo-dashboard/?embed=1')"))errors.push('SEO embed path is not environment-aware');
if(!seo.includes('ResizeObserver')||!seo.includes('mapDocumentUrl'))errors.push('isolated SEO embed contract missing');
for(const [name,source] of Object.entries(moduleSources)){
  if(name!=='shared'&&source.includes('2026-07-15-control-center-editorial-v1'))errors.push(`stale shared/module cache version in ${name}`);
  if(source.includes('2026-07-16-inbox-writeback-v3')||source.includes('2026-07-16-inbox-writeback-v4'))errors.push(`stale inbox-only cache version in ${name}`);
  for(const match of source.matchAll(/from\s+['"](\.\/[^'"]+\.js(?:\?[^'"]+)?)['"]/g))if(!match[1].includes('?v='))errors.push(`unversioned module import in ${name}: ${match[1]}`);
}
if(errors.length){console.error('=== Control Center Frontend Contract: FAILED ===');for(const error of errors)console.error('-',error);process.exit(1);}console.log('=== Control Center Frontend Contract: OK ===');
