<?php
declare(strict_types=1);

function be_startpartner_gate4_automatic_onboarding_items(array $gate3,string $operator='gate3-readback'):array
{
    $pilot=$gate3['pilot']??null;if(!is_array($pilot))return[];
    $auto=['terms_confirmed'=>['Gate-3 terms acceptance exists.',(string)($gate3['terms_acceptance']['id']??'')],'organizer_linked'=>['Gate-3 organizer link exists.',(string)($gate3['organizer']['id']??'')],'contact_confirmed'=>['Partner contact snapshot exists.',(string)($pilot['partner_contact_email_snapshot']??'')],'pilot_entitlement_readback'=>['Pilot entitlement was read back.',(string)($gate3['entitlement']['id']??'')],'service_scope_confirmed'=>['Normalized Gate-3 scopes exist.','gate3-scopes'],'sources_recorded'=>['Source-care scope was recorded in Gate 3.','automatic-source'],'maintenance_path_agreed'=>['Maintenance scope was recorded in Gate 3.','maintenance-service']];
    $rows=[];foreach(BE_STARTPARTNER_GATE4_ONBOARDING_ITEMS as $key){$value=$auto[$key]??null;$rows[]=['item_key'=>$key,'status'=>$value!==null?'complete':'pending','is_required'=>1,'is_hard_blocker'=>1,'evidence_text'=>$value[0]??null,'evidence_reference'=>$value[1]??null,'operator_reference'=>$value!==null?$operator:null,'completed_at'=>null,'revision'=>0];}return$rows;
}
function be_startpartner_gate4_seed_onboarding_items(PDO $pdo,array $gate3,string $operator):void
{
    $pilot=$gate3['pilot']??null;if(!is_array($pilot))throw new DomainException('Gate-3 pilot is required.');$preview=array_column(be_startpartner_gate4_automatic_onboarding_items($gate3,$operator),null,'item_key');
    $statement=$pdo->prepare("INSERT INTO startpartner_pilot_onboarding_items (pilot_id,item_key,status,is_required,is_hard_blocker,evidence_text,evidence_reference,operator_reference,completed_at) VALUES (:pilot_id,:item_key,:status,1,1,:evidence_text,:evidence_reference,:operator_reference,:completed_at) ON DUPLICATE KEY UPDATE item_key=VALUES(item_key)");
    foreach(BE_STARTPARTNER_GATE4_ONBOARDING_ITEMS as $key){$row=$preview[$key];$statement->execute(['pilot_id'=>(string)$pilot['id'],'item_key'=>$key,'status'=>$row['status'],'evidence_text'=>$row['evidence_text'],'evidence_reference'=>$row['evidence_reference'],'operator_reference'=>$row['operator_reference'],'completed_at'=>$row['status']==='complete'?gmdate('Y-m-d H:i:s'):null]);}
}
function be_startpartner_gate4_onboarding_rows(PDO $pdo,string $pilotId):array{$s=$pdo->prepare('SELECT * FROM startpartner_pilot_onboarding_items WHERE pilot_id=:pilot_id ORDER BY id');$s->execute(['pilot_id'=>$pilotId]);return be_startpartner_gate4_required_item_rows($s->fetchAll(PDO::FETCH_ASSOC));}
function be_startpartner_gate4_content_rows(PDO $pdo,string $pilotId):array{$s=$pdo->prepare('SELECT pcl.*,s.status AS submission_status,s.title,s.start_date,s.location_name,s.payment_kind,s.requested_model_key,s.approved_at AS submission_approved_at FROM startpartner_pilot_content_links pcl INNER JOIN submissions s ON s.id=pcl.submission_id WHERE pcl.pilot_id=:pilot_id ORDER BY pcl.created_at,pcl.id');$s->execute(['pilot_id'=>$pilotId]);return$s->fetchAll(PDO::FETCH_ASSOC);}
function be_startpartner_gate4_measurement_rows(PDO $pdo,string $pilotId):array{$s=$pdo->prepare('SELECT * FROM startpartner_pilot_measurement_preflights WHERE pilot_id=:pilot_id ORDER BY checked_at DESC,id DESC');$s->execute(['pilot_id'=>$pilotId]);$rows=$s->fetchAll(PDO::FETCH_ASSOC);foreach($rows as &$row){$row['evidence']=json_decode((string)$row['evidence_json'],true);unset($row['evidence_json']);}unset($row);return$rows;}
function be_startpartner_gate4_distribution_rows(PDO $pdo,string $pilotId):array{$s=$pdo->prepare('SELECT * FROM startpartner_pilot_distribution_commitments WHERE pilot_id=:pilot_id ORDER BY planned_at,created_at,id');$s->execute(['pilot_id'=>$pilotId]);return$s->fetchAll(PDO::FETCH_ASSOC);}
function be_startpartner_gate4_usage_rows(PDO $pdo,string $pilotId):array{$s=$pdo->prepare('SELECT * FROM startpartner_pilot_usages WHERE pilot_id=:pilot_id ORDER BY id');$s->execute(['pilot_id'=>$pilotId]);return$s->fetchAll(PDO::FETCH_ASSOC);}
function be_startpartner_gate4_state(PDO $pdo,string $candidateId,bool $includeEvents=true):array
{
    be_startpartner_gate4_require_schema($pdo);$gate3=be_startpartner_gate3_state($pdo,$candidateId,$includeEvents);$pilot=$gate3['pilot']??null;
    if(!is_array($pilot))return['complete'=>false,'phase'=>'gate3_required','pilot'=>null,'onboarding'=>be_startpartner_gate4_onboarding_readiness([]),'content_links'=>[],'measurement_preflights'=>[],'distribution_commitments'=>[],'usages'=>[],'first_content'=>null,'activation_ready'=>false,'active'=>false,'blockers'=>[['code'=>'gate3_pilot_required','message'=>'Gate 3 muss vor dem Onboarding abgeschlossen sein.']]];
    $pilotId=(string)$pilot['id'];$rows=be_startpartner_gate4_onboarding_rows($pdo,$pilotId);$persisted=count(array_filter($rows,static fn(array $row):bool=>(int)($row['revision']??0)>0))>0;if(!$persisted)$rows=be_startpartner_gate4_automatic_onboarding_items($gate3);$onboarding=be_startpartner_gate4_onboarding_readiness($rows);
    $content=be_startpartner_gate4_content_rows($pdo,$pilotId);$measurements=be_startpartner_gate4_measurement_rows($pdo,$pilotId);$distribution=be_startpartner_gate4_distribution_rows($pdo,$pilotId);$usages=be_startpartner_gate4_usage_rows($pdo,$pilotId);
    $first=null;foreach($content as $row)if(in_array((string)$row['status'],['editorial_ready','approved'],true)){$first=$row;break;}
    $measurement=null;foreach($measurements as $row)if((string)$row['status']==='ready'&&($first===null||(string)$row['content_link_id']===(string)$first['id'])){$measurement=$row;break;}
    $reach=null;foreach($distribution as $row)if(in_array((string)$row['status'],['ready','completed'],true)){$reach=$row;break;}
    $blockers=$onboarding['blockers'];if($first===null)$blockers[]=['code'=>'first_content_not_ready','message'=>'Der erste Inhalt ist noch nicht redaktionell bereit.'];if($measurement===null)$blockers[]=['code'=>'measurement_not_ready','message'=>'Die Pilot-, Organizer- und Inhaltsmessung ist noch nicht belegt.'];if($reach===null)$blockers[]=['code'=>'distribution_not_ready','message'=>'Der Partner-Reichweitenstart ist noch nicht konkret vorbereitet.'];$entitlement=$gate3['entitlement']??null;if(!is_array($entitlement))$blockers[]=['code'=>'pilot_entitlement_missing','message'=>'Pilotberechtigung fehlt.'];
    $status=(string)$pilot['status'];$active=$status==='active'&&is_array($entitlement)&&(string)$entitlement['status']==='active'&&$first!==null&&(string)$first['status']==='approved';$ready=!$active&&in_array($status,['onboarding','activation_ready'],true)&&$blockers===[]&&is_array($entitlement)&&(string)$entitlement['status']==='pending_activation';
    return['complete'=>$active,'phase'=>$active?'active':($ready?'activation_ready':'onboarding'),'pilot'=>$pilot,'onboarding'=>$onboarding,'content_links'=>$content,'measurement_preflights'=>$measurements,'distribution_commitments'=>$distribution,'usages'=>$usages,'first_content'=>$first,'ready_measurement'=>$measurement,'ready_distribution'=>$reach,'activation_ready'=>$ready,'active'=>$active,'blockers'=>$blockers,'capacity'=>be_startpartner_gate4_capacity($pdo)];
}
function be_startpartner_gate4_candidate_detail(PDO $pdo,string $candidateId,bool $includeEvents=true):array
{
    $candidate=be_startpartner_gate3_candidate_detail($pdo,$candidateId,$includeEvents);$candidate['gate4']=be_startpartner_gate4_state($pdo,$candidateId,$includeEvents);if(is_array($candidate['gate4']['pilot']??null)){$candidate['gate3']['complete']=true;$candidate['gate3']['blockers']=[];}$candidate['capacity']=$candidate['gate4']['capacity'];return$candidate;
}
