#!/usr/bin/env python3
from pathlib import Path
import re
p=Path('.github/workflows/deploy-strato.yml')
s=p.read_text(encoding='utf-8')
s=s.replace('  workflow_dispatch:\n','  workflow_dispatch:\n    inputs:\n      full_repair:\n        description: "Vollständigen Reparatur-Deploy ausführen"\n        required: false\n        default: false\n        type: boolean\n',1)
prepare='''      # === BEGIN BLOCK: STAGING_CONTENT_HASH_DELTA_V1 ===\n      - name: Prepare staging content-hash delta\n        shell: bash\n        env:\n          REQUEST_FULL_REPAIR: ${{ github.event_name == 'workflow_dispatch' && inputs.full_repair || false }}\n        run: |\n          set -euo pipefail\n          MODE=full\n          if [ "$DEPLOY_ENV_NAME" = staging ]; then MODE=delta; [ "$REQUEST_FULL_REPAIR" = true ] && MODE=full_repair; fi\n          REMOTE=/tmp/deploy-manifest.json\n          if [ "$MODE" = delta ]; then curl -fsSL --retry 2 --connect-timeout 10 "$SITE_ORIGIN/meta/deploy-manifest.json?run=$GITHUB_RUN_ID" -o "$REMOTE" || { echo '{}' > "$REMOTE"; MODE=full_repair; }; else echo '{}' > "$REMOTE"; fi\n          echo "DEPLOY_MODE=$MODE" >> "$GITHUB_ENV"\n          export MODE REMOTE\n          python - <<'PY'\n          import hashlib,json,os,shutil\n          from pathlib import Path\n          src=Path('deploy'); assets=Path('deploy-assets'); entry=Path('deploy-entry')\n          for d in (assets,entry): shutil.rmtree(d,ignore_errors=True); d.mkdir(parents=True)\n          def sha(p):\n              h=hashlib.sha256()\n              with p.open('rb') as f:\n                  for c in iter(lambda:f.read(1048576),b''): h.update(c)\n              return h.hexdigest()\n          cur={p.relative_to(src).as_posix():sha(p) for p in src.rglob('*') if p.is_file() and p.relative_to(src).as_posix()!='meta/deploy-manifest.json'}\n          try:\n              old=json.loads(Path(os.environ['REMOTE']).read_text()).get('files',{})\n              if not isinstance(old,dict): old={}\n          except Exception: old={}\n          mode=os.environ['MODE']; changed=set(cur) if mode!='delta' else {k for k,v in cur.items() if old.get(k)!=v}; deleted=(set(old)-set(cur)) if mode!='full' else set()\n          if 'api/_config.php' in cur: changed.add('api/_config.php')\n          late={k for k in cur if k.endswith('.html')}|{'meta/build.txt'}\n          for rel in changed:\n              a=src/rel; root=entry if rel in late else assets; b=root/rel; b.parent.mkdir(parents=True,exist_ok=True); shutil.copy2(a,b)\n          manifest={'schema':1,'build':os.getenv('BUILD_ID',''),'environment':os.getenv('DEPLOY_ENV_NAME',''),'files':cur}\n          m=entry/'meta/deploy-manifest.json'; m.parent.mkdir(parents=True,exist_ok=True); m.write_text(json.dumps(manifest,sort_keys=True,indent=2)+'\\n')\n          lines=[]\n          for rel in sorted(deleted):\n              if any(c in rel for c in ['"','\\n','\\r']): raise SystemExit('unsafe path')\n              lines.append(f'rm -f "{rel}"')\n          Path('deploy-delete.lftp').write_text('\\n'.join(lines)+('\\n' if lines else ''))\n          print('mode',mode,'changed',len(changed),'deleted',len(deleted))\n          PY\n      # === END BLOCK: STAGING_CONTENT_HASH_DELTA_V1 ===\n\n'''
if 'STAGING_CONTENT_HASH_DELTA_V1' not in s: s=s.replace('      - name: Install lftp\n',prepare+'      - name: Install lftp\n',1)
new='''      # === BEGIN BLOCK: STRATO_UPLOAD_DELTA_V1 ===\n      - name: Upload changed assets to STRATO via SFTP\n        timeout-minutes: 30\n        shell: bash\n        env:\n          STRATO_FTP_SERVER: ${{ secrets.STRATO_FTP_SERVER }}\n          STRATO_FTP_USERNAME: ${{ secrets.STRATO_FTP_USERNAME }}\n          STRATO_FTP_PASSWORD: ${{ secrets.STRATO_FTP_PASSWORD }}\n        run: |\n          set -euo pipefail\n          DEL="$(cat deploy-delete.lftp 2>/dev/null || true)"\n          lftp -u "$STRATO_FTP_USERNAME","$STRATO_FTP_PASSWORD" "sftp://$STRATO_FTP_SERVER" <<LFTP\n          set sftp:auto-confirm yes\n          set cmd:fail-exit yes\n          set net:timeout 25\n          set net:max-retries 4\n          set net:reconnect-interval-base 2\n          set net:reconnect-interval-max 15\n          cd $DEPLOY_TARGET_DIR\n          mirror -R --parallel=8 --verbose deploy-assets/ .\n          $DEL\n          bye\n          LFTP\n\n      - name: Publish HTML and build marker last\n        timeout-minutes: 8\n        shell: bash\n        env:\n          STRATO_FTP_SERVER: ${{ secrets.STRATO_FTP_SERVER }}\n          STRATO_FTP_USERNAME: ${{ secrets.STRATO_FTP_USERNAME }}\n          STRATO_FTP_PASSWORD: ${{ secrets.STRATO_FTP_PASSWORD }}\n        run: |\n          set -euo pipefail\n          lftp -u "$STRATO_FTP_USERNAME","$STRATO_FTP_PASSWORD" "sftp://$STRATO_FTP_SERVER" <<LFTP\n          set sftp:auto-confirm yes\n          set cmd:fail-exit yes\n          set net:timeout 25\n          set net:max-retries 4\n          cd $DEPLOY_TARGET_DIR\n          mirror -R --parallel=6 --verbose deploy-entry/ .\n          bye\n          LFTP\n      # === END BLOCK: STRATO_UPLOAD_DELTA_V1 ==='''
pat=re.compile(r'      # === BEGIN BLOCK: STRATO_UPLOAD_V6.*?      # === END BLOCK: STRATO_UPLOAD_V6 ===',re.S)
if pat.search(s): s=pat.sub(new,s,1)
elif 'STRATO_UPLOAD_DELTA_V1' not in s: raise SystemExit('upload block missing')
p.write_text(s,encoding='utf-8')
